classdef window_type
    enumeration
        Rectangle, ...
        Triangle, ...
        Parzen, ...
        Welch, ...
        Hanning, ...
        Hamming, ...
        Blackman, ...
        Nuttall, ...
        BlackmanNuttall, ...
        BlackmanHarris, ...
        FlatTop, ...
        Cosine, ...
        Gaussian, ...
        GeneralNormal, ...
        Tukey, ...
        PlankTaper, ...
        Slepian, ...
        Kaiser, ...
        DolphChebyshev, ...
        UltraSpherical, ...
        Poisson, ...
        BartlettHann, ...
        PlankBessel, ...
        HannPoisson, ...
        Lanczos
    end
end

